apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  apiUrl: https://ecb49462.live.dynatrace.com/api
  oneAgent:
    classicFullStack:
      enabled: true
