name: CI Pipeline
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm test  # Runs Jest tests
  ai-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: testimio/action-runner@v1
        with:
          testim-api-key: ${{ secrets.TESTIM_API_KEY }}
          testim-project-id: ${{ secrets.TESTIM_PROJECT_ID }}
          branch: main
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --org=your-org --project-name=ai-cicd-demo
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}